/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinEventIdRouteImport } from './routes/join.$eventId'
import { Route as AuthenticatedOrganizerRouteImport } from './routes/_authenticated/organizer'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedEventNewRouteImport } from './routes/_authenticated/event.new'
import { Route as AuthenticatedEventEventIdIndexRouteImport } from './routes/_authenticated/event.$eventId.index'
import { Route as AuthenticatedEventEventIdShareRouteImport } from './routes/_authenticated/event.$eventId.share'
import { Route as AuthenticatedEventEventIdProfileRouteImport } from './routes/_authenticated/event.$eventId.profile'
import { Route as AuthenticatedEventEventIdAttendeeMembershipIdRouteImport } from './routes/_authenticated/event.$eventId.attendee.$membershipId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinEventIdRoute = JoinEventIdRouteImport.update({
  id: '/join/$eventId',
  path: '/join/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizerRoute = AuthenticatedOrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventNewRoute = AuthenticatedEventNewRouteImport.update({
  id: '/event/new',
  path: '/event/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventEventIdIndexRoute =
  AuthenticatedEventEventIdIndexRouteImport.update({
    id: '/event/$eventId/',
    path: '/event/$eventId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventEventIdShareRoute =
  AuthenticatedEventEventIdShareRouteImport.update({
    id: '/event/$eventId/share',
    path: '/event/$eventId/share',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventEventIdProfileRoute =
  AuthenticatedEventEventIdProfileRouteImport.update({
    id: '/event/$eventId/profile',
    path: '/event/$eventId/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventEventIdAttendeeMembershipIdRoute =
  AuthenticatedEventEventIdAttendeeMembershipIdRouteImport.update({
    id: '/event/$eventId/attendee/$membershipId',
    path: '/event/$eventId/attendee/$membershipId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/organizer': typeof AuthenticatedOrganizerRoute
  '/join/$eventId': typeof JoinEventIdRoute
  '/event/new': typeof AuthenticatedEventNewRoute
  '/event/$eventId/profile': typeof AuthenticatedEventEventIdProfileRoute
  '/event/$eventId/share': typeof AuthenticatedEventEventIdShareRoute
  '/event/$eventId/': typeof AuthenticatedEventEventIdIndexRoute
  '/event/$eventId/attendee/$membershipId': typeof AuthenticatedEventEventIdAttendeeMembershipIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/organizer': typeof AuthenticatedOrganizerRoute
  '/join/$eventId': typeof JoinEventIdRoute
  '/event/new': typeof AuthenticatedEventNewRoute
  '/event/$eventId/profile': typeof AuthenticatedEventEventIdProfileRoute
  '/event/$eventId/share': typeof AuthenticatedEventEventIdShareRoute
  '/event/$eventId': typeof AuthenticatedEventEventIdIndexRoute
  '/event/$eventId/attendee/$membershipId': typeof AuthenticatedEventEventIdAttendeeMembershipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/organizer': typeof AuthenticatedOrganizerRoute
  '/join/$eventId': typeof JoinEventIdRoute
  '/_authenticated/event/new': typeof AuthenticatedEventNewRoute
  '/_authenticated/event/$eventId/profile': typeof AuthenticatedEventEventIdProfileRoute
  '/_authenticated/event/$eventId/share': typeof AuthenticatedEventEventIdShareRoute
  '/_authenticated/event/$eventId/': typeof AuthenticatedEventEventIdIndexRoute
  '/_authenticated/event/$eventId/attendee/$membershipId': typeof AuthenticatedEventEventIdAttendeeMembershipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/terms'
    | '/app'
    | '/organizer'
    | '/join/$eventId'
    | '/event/new'
    | '/event/$eventId/profile'
    | '/event/$eventId/share'
    | '/event/$eventId/'
    | '/event/$eventId/attendee/$membershipId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/terms'
    | '/app'
    | '/organizer'
    | '/join/$eventId'
    | '/event/new'
    | '/event/$eventId/profile'
    | '/event/$eventId/share'
    | '/event/$eventId'
    | '/event/$eventId/attendee/$membershipId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/app'
    | '/_authenticated/organizer'
    | '/join/$eventId'
    | '/_authenticated/event/new'
    | '/_authenticated/event/$eventId/profile'
    | '/_authenticated/event/$eventId/share'
    | '/_authenticated/event/$eventId/'
    | '/_authenticated/event/$eventId/attendee/$membershipId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  JoinEventIdRoute: typeof JoinEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$eventId': {
      id: '/join/$eventId'
      path: '/join/$eventId'
      fullPath: '/join/$eventId'
      preLoaderRoute: typeof JoinEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organizer': {
      id: '/_authenticated/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof AuthenticatedOrganizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/event/new': {
      id: '/_authenticated/event/new'
      path: '/event/new'
      fullPath: '/event/new'
      preLoaderRoute: typeof AuthenticatedEventNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/event/$eventId/': {
      id: '/_authenticated/event/$eventId/'
      path: '/event/$eventId'
      fullPath: '/event/$eventId/'
      preLoaderRoute: typeof AuthenticatedEventEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/event/$eventId/share': {
      id: '/_authenticated/event/$eventId/share'
      path: '/event/$eventId/share'
      fullPath: '/event/$eventId/share'
      preLoaderRoute: typeof AuthenticatedEventEventIdShareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/event/$eventId/profile': {
      id: '/_authenticated/event/$eventId/profile'
      path: '/event/$eventId/profile'
      fullPath: '/event/$eventId/profile'
      preLoaderRoute: typeof AuthenticatedEventEventIdProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/event/$eventId/attendee/$membershipId': {
      id: '/_authenticated/event/$eventId/attendee/$membershipId'
      path: '/event/$eventId/attendee/$membershipId'
      fullPath: '/event/$eventId/attendee/$membershipId'
      preLoaderRoute: typeof AuthenticatedEventEventIdAttendeeMembershipIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedOrganizerRoute: typeof AuthenticatedOrganizerRoute
  AuthenticatedEventNewRoute: typeof AuthenticatedEventNewRoute
  AuthenticatedEventEventIdProfileRoute: typeof AuthenticatedEventEventIdProfileRoute
  AuthenticatedEventEventIdShareRoute: typeof AuthenticatedEventEventIdShareRoute
  AuthenticatedEventEventIdIndexRoute: typeof AuthenticatedEventEventIdIndexRoute
  AuthenticatedEventEventIdAttendeeMembershipIdRoute: typeof AuthenticatedEventEventIdAttendeeMembershipIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedOrganizerRoute: AuthenticatedOrganizerRoute,
  AuthenticatedEventNewRoute: AuthenticatedEventNewRoute,
  AuthenticatedEventEventIdProfileRoute: AuthenticatedEventEventIdProfileRoute,
  AuthenticatedEventEventIdShareRoute: AuthenticatedEventEventIdShareRoute,
  AuthenticatedEventEventIdIndexRoute: AuthenticatedEventEventIdIndexRoute,
  AuthenticatedEventEventIdAttendeeMembershipIdRoute:
    AuthenticatedEventEventIdAttendeeMembershipIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  JoinEventIdRoute: JoinEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
