/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinEventIdRouteImport } from './routes/join.$eventId'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedEventEventIdIndexRouteImport } from './routes/_authenticated/event.$eventId.index'
import { Route as AuthenticatedEventEventIdProfileRouteImport } from './routes/_authenticated/event.$eventId.profile'
import { Route as AuthenticatedEventEventIdAttendeeMembershipIdRouteImport } from './routes/_authenticated/event.$eventId.attendee.$membershipId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinEventIdRoute = JoinEventIdRouteImport.update({
  id: '/join/$eventId',
  path: '/join/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventEventIdIndexRoute =
  AuthenticatedEventEventIdIndexRouteImport.update({
    id: '/event/$eventId/',
    path: '/event/$eventId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventEventIdProfileRoute =
  AuthenticatedEventEventIdProfileRouteImport.update({
    id: '/event/$eventId/profile',
    path: '/event/$eventId/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventEventIdAttendeeMembershipIdRoute =
  AuthenticatedEventEventIdAttendeeMembershipIdRouteImport.update({
    id: '/event/$eventId/attendee/$membershipId',
    path: '/event/$eventId/attendee/$membershipId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/join/$eventId': typeof JoinEventIdRoute
  '/event/$eventId/profile': typeof AuthenticatedEventEventIdProfileRoute
  '/event/$eventId/': typeof AuthenticatedEventEventIdIndexRoute
  '/event/$eventId/attendee/$membershipId': typeof AuthenticatedEventEventIdAttendeeMembershipIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/join/$eventId': typeof JoinEventIdRoute
  '/event/$eventId/profile': typeof AuthenticatedEventEventIdProfileRoute
  '/event/$eventId': typeof AuthenticatedEventEventIdIndexRoute
  '/event/$eventId/attendee/$membershipId': typeof AuthenticatedEventEventIdAttendeeMembershipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/join/$eventId': typeof JoinEventIdRoute
  '/_authenticated/event/$eventId/profile': typeof AuthenticatedEventEventIdProfileRoute
  '/_authenticated/event/$eventId/': typeof AuthenticatedEventEventIdIndexRoute
  '/_authenticated/event/$eventId/attendee/$membershipId': typeof AuthenticatedEventEventIdAttendeeMembershipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/join/$eventId'
    | '/event/$eventId/profile'
    | '/event/$eventId/'
    | '/event/$eventId/attendee/$membershipId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/join/$eventId'
    | '/event/$eventId/profile'
    | '/event/$eventId'
    | '/event/$eventId/attendee/$membershipId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/join/$eventId'
    | '/_authenticated/event/$eventId/profile'
    | '/_authenticated/event/$eventId/'
    | '/_authenticated/event/$eventId/attendee/$membershipId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinEventIdRoute: typeof JoinEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$eventId': {
      id: '/join/$eventId'
      path: '/join/$eventId'
      fullPath: '/join/$eventId'
      preLoaderRoute: typeof JoinEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/event/$eventId/': {
      id: '/_authenticated/event/$eventId/'
      path: '/event/$eventId'
      fullPath: '/event/$eventId/'
      preLoaderRoute: typeof AuthenticatedEventEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/event/$eventId/profile': {
      id: '/_authenticated/event/$eventId/profile'
      path: '/event/$eventId/profile'
      fullPath: '/event/$eventId/profile'
      preLoaderRoute: typeof AuthenticatedEventEventIdProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/event/$eventId/attendee/$membershipId': {
      id: '/_authenticated/event/$eventId/attendee/$membershipId'
      path: '/event/$eventId/attendee/$membershipId'
      fullPath: '/event/$eventId/attendee/$membershipId'
      preLoaderRoute: typeof AuthenticatedEventEventIdAttendeeMembershipIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedEventEventIdProfileRoute: typeof AuthenticatedEventEventIdProfileRoute
  AuthenticatedEventEventIdIndexRoute: typeof AuthenticatedEventEventIdIndexRoute
  AuthenticatedEventEventIdAttendeeMembershipIdRoute: typeof AuthenticatedEventEventIdAttendeeMembershipIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedEventEventIdProfileRoute: AuthenticatedEventEventIdProfileRoute,
  AuthenticatedEventEventIdIndexRoute: AuthenticatedEventEventIdIndexRoute,
  AuthenticatedEventEventIdAttendeeMembershipIdRoute:
    AuthenticatedEventEventIdAttendeeMembershipIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinEventIdRoute: JoinEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
